_core:
  default_config_hash: IQjf_ytthngZTAk_MU8-74VecArWD3G5g0oEH6PM6GA
toolbar_items:
  - devel.cache_clear
  - devel.run_cron
  - devel.menu_rebuild
  - devel.reinstall
  - devel.route_info
  - devel.configs_list
  - devel.state_system_page
